name: Create Test Branch Deployment

on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  deploy:
    name: Build and Upload to S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: What is the version number?
        run: echo Creating test deployment for ${GITHUB_REF:11} branch.
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8080'
      - name: Create Build
        run: |
          npm install
          npm run build
      - name: Deploy Build
        uses: blueraster/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './dist'
          DEST_DIR: 'gfw-mapbuilder/pull-requests/${{GITHUB_REF:11}}'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.MB_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MB_AWS_SECRET_ACCESS_KEY }}
